### ISSUE TITLE
Make it possible to write version file even if version didn't change

### ISSUE THREAD

**Issue by leifg** [go-semantic-release/go-semantic-release#11]
running `~/semantic-release -vf` when the version didn't change will not create a version file. I think it's particular useful for testing the workflow (together with `-noci`).

I haven't seen a flag that let's you specify if you want to write the version file.

**Comment by ssorathia** [comment]
I like this idea as well.  Coupled with #8 this could help us with an issue we have where sometimes we are unable to push a docker image, and when that fails, there is no easy way to push the build.  If open, I could potentially open a PR that would allow a flag to be passed to allow this.

**Comment by christophwitzko** [comment]
Hey all, a version file is only written when a new version has been released and the `-vf` flag is set. The version file should be an indicator to determine if a new version got released. That's why I am not feeling comfortable adding this option.

**Comment by ssorathia** [comment]
Though it's closed, how would you recommend handling the situation I described?  The version has been created in github, and I'm using this tool to determine this, but if for some reason the docker push for that version doesn't complete properly, I don't really have a good way to "fix" this beyond deleting the version in github (which could be done, but generally I don't like doing this)

**Comment by christophwitzko** [comment]
That is something that also had happened to me. I fixed this most of the time by pushing an empty commit. (not the cleanest solution, but the fastest)
